# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('years_playing', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('introduction', models.TextField()),
            ],
        ),
    ]
