# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170615_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='introduction',
            new_name='tell_us_about_yourself',
        ),
    ]
